name: UntetheredMac

packages:
  UntetheredCore:
    path: ../Shared

options:
  bundleIdPrefix: com.910labs
  deploymentTarget:
    macOS: "15.0"
  developmentLanguage: en
  createIntermediateGroups: true
  generateEmptyDirectories: false

settings:
  base:
    DEVELOPMENT_TEAM: REDACTED_TEAM_ID_2
    CODE_SIGN_STYLE: Automatic
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: 1
    MACOSX_DEPLOYMENT_TARGET: "15.0"
  configs:
    Debug:
      BuildIndependentTargetsInParallel: true
    Release:
      BuildIndependentTargetsInParallel: true

targets:
  UntetheredMac:
    type: application
    platform: macOS
    deploymentTarget: "15.0"
    supportedDestinations:
      - macOS
    sources:
      - path: Sources
        excludes:
          - "*.md"
    resources:
      - Resources/Assets.xcassets
    info:
      path: Resources/Info.plist
      properties:
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleDisplayName: Untethered
        CFBundleIconName: AppIcon
        NSMicrophoneUsageDescription: Untethered needs microphone access for voice input to Claude.
        NSSpeechRecognitionUsageDescription: Untethered uses speech recognition to transcribe your voice commands.
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.910labs.untethered.mac
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        INFOPLIST_FILE: Resources/Info.plist
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/../Frameworks"
        ENABLE_HARDENED_RUNTIME: YES
      configs:
        Debug:
          DEVELOPMENT_TEAM: REDACTED_TEAM_ID
        Release:
          DEVELOPMENT_TEAM: REDACTED_TEAM_ID
    dependencies:
      - package: UntetheredCore

  UntetheredMacTests:
    type: bundle.unit-test
    platform: macOS
    deploymentTarget: "15.0"
    sources:
      - Tests
    dependencies:
      - package: UntetheredCore
      - target: UntetheredMac
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.910labs.untethered.macTests
        GENERATE_INFOPLIST_FILE: YES

schemes:
  UntetheredMac:
    build:
      targets:
        UntetheredMac: all
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - name: UntetheredMacTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
      customArchiveName: UntetheredMac
      revealArchiveInOrganizer: true
