name: VoiceCode

options:
  bundleIdPrefix: dev.910labs
  deploymentTarget:
    iOS: "18.5"
  developmentLanguage: en
  createIntermediateGroups: true
  generateEmptyDirectories: false

settings:
  base:
    DEVELOPMENT_TEAM: REDACTED_TEAM_ID_2
    CODE_SIGN_STYLE: Automatic
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: 68
    IPHONEOS_DEPLOYMENT_TARGET: "18.5"
  configs:
    Debug:
      BuildIndependentTargetsInParallel: true
    Release:
      BuildIndependentTargetsInParallel: true

targets:
  VoiceCode:
    type: application
    platform: iOS
    deploymentTarget: "18.5"
    supportedDestinations:
      - iOS
    sources:
      - path: VoiceCode
        excludes:
          - "*.md"
    resources:
      - VoiceCode/Assets.xcassets
      - VoiceCode/VoiceCode.xcdatamodeld
      - VoiceCode/PrivacyInfo.xcprivacy
    info:
      path: VoiceCode/Info.plist
      properties:
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleDisplayName: Untethered
        CFBundleIconName: AppIcon
        NSMicrophoneUsageDescription: Untethered needs microphone access for voice input to control Claude.
        NSSpeechRecognitionUsageDescription: Untethered needs speech recognition to transcribe your voice commands.
        NSLocalNetworkUsageDescription: Untethered needs to connect to your backend server on your local network to send voice commands and receive Claude Code responses.
        NSPrivacyPolicyURL: https://raw.githubusercontent.com/travisbrown/voice-code/main/docs/privacy-policy.md
        UIBackgroundModes:
          - audio
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: true
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UILaunchScreen:
          UIColorName: ""
          UIImageName: ""
        ITSAppUsesNonExemptEncryption: false
    entitlements:
      path: VoiceCode/VoiceCode.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.910labs.untethered.resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: dev.910labs.voice-code
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        INFOPLIST_FILE: VoiceCode/Info.plist
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks"
      configs:
        Debug:
          DEVELOPMENT_TEAM: REDACTED_TEAM_ID
        Release:
          DEVELOPMENT_TEAM: REDACTED_TEAM_ID
    preBuildScripts: []
    postBuildScripts: []
    dependencies:
      - target: VoiceCodeShareExtension
        embed: true

  VoiceCodeShareExtension:
    type: app-extension
    platform: iOS
    deploymentTarget: "18.5"
    sources:
      - path: VoiceCodeShareExtension
        excludes:
          - "*.md"
    resources:
      - VoiceCodeShareExtension/Base.lproj
    info:
      path: VoiceCodeShareExtension/Info.plist
      properties:
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleDisplayName: Untethered
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
        NSExtension:
          NSExtensionAttributes:
            NSExtensionActivationRule:
              NSExtensionActivationSupportsFileWithMaxCount: 10
              NSExtensionActivationSupportsText: true
              NSExtensionActivationSupportsWebURLWithMaxCount: 10
              NSExtensionActivationSupportsImageWithMaxCount: 10
          NSExtensionPrincipalClass: $(PRODUCT_MODULE_NAME).ShareViewController
          NSExtensionPointIdentifier: com.apple.share-services
    entitlements:
      path: VoiceCodeShareExtension/VoiceCodeShareExtension.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.910labs.untethered.resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: dev.910labs.voice-code.VoiceCodeShareExtension
        INFOPLIST_FILE: VoiceCodeShareExtension/Info.plist
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks @executable_path/../../Frameworks"

  VoiceCodeTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "18.5"
    sources:
      - VoiceCodeTests
    resources:
      - VoiceCodeTests/Fixtures
    dependencies:
      - target: VoiceCode
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: dev.910labs.voice-codeTests
        GENERATE_INFOPLIST_FILE: YES

  VoiceCodeUITests:
    type: bundle.ui-testing
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - VoiceCodeUITests
    dependencies:
      - target: VoiceCode
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: dev.910labs.voice-codeUITests
        GENERATE_INFOPLIST_FILE: YES

schemes:
  VoiceCode:
    build:
      targets:
        VoiceCode: all
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - name: VoiceCodeTests
        - name: VoiceCodeUITests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
      customArchiveName: VoiceCode
      revealArchiveInOrganizer: true
      preActions: []
      postActions: []
